sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - models

dist: trusty
language: python

python:
  - "3.6"
install: source continuous_integration/install.sh
script: python -m unittest tests.basic